export const GOOGLE_FONT_OPTIONS = Object.freeze([
  ['Inter, "Noto Sans Georgian", system-ui, sans-serif', 'Inter'],
  ['Roboto, "Noto Sans Georgian", Arial, sans-serif', 'Roboto'],
  ['Open Sans, "Noto Sans Georgian", Arial, sans-serif', 'Open Sans'],
  ['Montserrat, "Noto Sans Georgian", Arial, sans-serif', 'Montserrat'],
  ['Poppins, "Noto Sans Georgian", Arial, sans-serif', 'Poppins'],
  ['Lato, "Noto Sans Georgian", Arial, sans-serif', 'Lato'],
  ['Nunito Sans, "Noto Sans Georgian", Arial, sans-serif', 'Nunito Sans'],
  ['Raleway, "Noto Sans Georgian", Arial, sans-serif', 'Raleway'],
  ['Oswald, "Noto Sans Georgian", Arial, sans-serif', 'Oswald'],
  ['Bebas Neue, "Noto Sans Georgian", Arial, sans-serif', 'Bebas Neue'],
  ['Playfair Display, "Noto Serif Georgian", Georgia, serif', 'Playfair Display'],
  ['Merriweather, "Noto Serif Georgian", Georgia, serif', 'Merriweather'],
  ['Cormorant Garamond, "Noto Serif Georgian", Georgia, serif', 'Cormorant Garamond'],
  ['Libre Baskerville, "Noto Serif Georgian", Georgia, serif', 'Libre Baskerville'],
  ['Noto Sans Georgian, Inter, system-ui, sans-serif', 'Noto Sans Georgian'],
  ['Noto Serif Georgian, Georgia, serif', 'Noto Serif Georgian'],
]);

export const FONT_STACKS = Object.freeze({
  modernSans: GOOGLE_FONT_OPTIONS[0][0],
  premiumSerif: GOOGLE_FONT_OPTIONS[10][0],
  georgianClean: GOOGLE_FONT_OPTIONS[14][0],
  boldPromo: GOOGLE_FONT_OPTIONS[9][0],
  classicMenu: GOOGLE_FONT_OPTIONS[11][0],
});

export const FONT_PRESETS = Object.freeze({
  cleanModern: {
    categoryFontFamily: FONT_STACKS.modernSans,
    dishTitleFontFamily: FONT_STACKS.modernSans,
    descriptionFontFamily: FONT_STACKS.modernSans,
    priceFontFamily: FONT_STACKS.modernSans,
    badgeFontFamily: FONT_STACKS.modernSans,
    headerFooterFontFamily: FONT_STACKS.modernSans,
    categoryFontWeight: 850,
    dishTitleFontWeight: 800,
    descriptionFontWeight: 500,
    priceFontWeight: 900,
    badgeFontWeight: 900,
    categoryLetterSpacing: -0.02,
    dishTitleLetterSpacing: -0.01,
    priceLetterSpacing: 0,
    categoryUppercase: false,
    dishTitleUppercase: false,
    categoryTitleStyle: 'plain',
  },
  premiumRestaurant: {
    categoryFontFamily: FONT_STACKS.premiumSerif,
    dishTitleFontFamily: FONT_STACKS.premiumSerif,
    descriptionFontFamily: FONT_STACKS.modernSans,
    priceFontFamily: FONT_STACKS.premiumSerif,
    badgeFontFamily: FONT_STACKS.modernSans,
    headerFooterFontFamily: FONT_STACKS.premiumSerif,
    categoryFontWeight: 700,
    dishTitleFontWeight: 700,
    descriptionFontWeight: 500,
    priceFontWeight: 800,
    badgeFontWeight: 850,
    categoryLetterSpacing: 0.04,
    dishTitleLetterSpacing: 0.01,
    priceLetterSpacing: 0.02,
    categoryUppercase: true,
    dishTitleUppercase: false,
    categoryTitleStyle: 'underline',
  },
  sushiPromo: {
    categoryFontFamily: FONT_STACKS.georgianClean,
    dishTitleFontFamily: FONT_STACKS.modernSans,
    descriptionFontFamily: FONT_STACKS.georgianClean,
    priceFontFamily: FONT_STACKS.modernSans,
    badgeFontFamily: FONT_STACKS.modernSans,
    headerFooterFontFamily: FONT_STACKS.georgianClean,
    categoryFontWeight: 900,
    dishTitleFontWeight: 850,
    descriptionFontWeight: 550,
    priceFontWeight: 950,
    badgeFontWeight: 950,
    categoryLetterSpacing: 0.03,
    dishTitleLetterSpacing: 0,
    priceLetterSpacing: -0.02,
    categoryUppercase: true,
    dishTitleUppercase: false,
    categoryTitleStyle: 'accentBar',
  },
  minimalGeorgian: {
    categoryFontFamily: FONT_STACKS.georgianClean,
    dishTitleFontFamily: FONT_STACKS.georgianClean,
    descriptionFontFamily: FONT_STACKS.georgianClean,
    priceFontFamily: FONT_STACKS.georgianClean,
    badgeFontFamily: FONT_STACKS.georgianClean,
    headerFooterFontFamily: FONT_STACKS.georgianClean,
    categoryFontWeight: 750,
    dishTitleFontWeight: 700,
    descriptionFontWeight: 500,
    priceFontWeight: 850,
    badgeFontWeight: 800,
    categoryLetterSpacing: 0,
    dishTitleLetterSpacing: 0,
    priceLetterSpacing: 0,
    categoryUppercase: false,
    dishTitleUppercase: false,
    categoryTitleStyle: 'centered',
  },
  boldDiscount: {
    categoryFontFamily: FONT_STACKS.boldPromo,
    dishTitleFontFamily: FONT_STACKS.modernSans,
    descriptionFontFamily: FONT_STACKS.modernSans,
    priceFontFamily: FONT_STACKS.boldPromo,
    badgeFontFamily: FONT_STACKS.boldPromo,
    headerFooterFontFamily: FONT_STACKS.modernSans,
    categoryFontWeight: 900,
    dishTitleFontWeight: 900,
    descriptionFontWeight: 650,
    priceFontWeight: 900,
    badgeFontWeight: 900,
    categoryLetterSpacing: 0.04,
    dishTitleLetterSpacing: 0.01,
    priceLetterSpacing: 0.02,
    categoryUppercase: true,
    dishTitleUppercase: true,
    categoryTitleStyle: 'pill',
  },
  classicMenu: {
    categoryFontFamily: FONT_STACKS.classicMenu,
    dishTitleFontFamily: FONT_STACKS.classicMenu,
    descriptionFontFamily: FONT_STACKS.classicMenu,
    priceFontFamily: FONT_STACKS.classicMenu,
    badgeFontFamily: FONT_STACKS.modernSans,
    headerFooterFontFamily: FONT_STACKS.classicMenu,
    categoryFontWeight: 700,
    dishTitleFontWeight: 700,
    descriptionFontWeight: 500,
    priceFontWeight: 800,
    badgeFontWeight: 850,
    categoryLetterSpacing: 0.02,
    dishTitleLetterSpacing: 0,
    priceLetterSpacing: 0,
    categoryUppercase: false,
    dishTitleUppercase: false,
    categoryTitleStyle: 'underline',
  },
});
